#!/bin/bash
# Basic parallel grep. Searches recursively over its arguments.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

set -e
set -o pipefail
declare -a args
declare -a grep_opts
declare -a find_opts
declare -a parallel_opts

declare -i want_binaries=0
declare -i want_vcs=0
declare -i want_autoconf=0
declare -i want_ugly=0
declare -i saw_dd=0
declare -i have_re=0
declare -i filenames_and_line_numbers=1
declare -i want_changelogs=0
declare -i want_build_files=0
declare -i want_backups=0
declare -i want_pager=0
declare -i max_args_per_grep=1000
re=

prgname=$(basename "$0")

err() {
    set +e
    fmt=$1
    shift
    printf >&2 '%s: '"$fmt"'\n' "$prgname" "$@"
    exit 1
}

if [[ -z $GREP ]] && type -p ggrep >/dev/null 2>&1; then
    GREP=ggrep
fi
: ${GREP=grep}

if [[ -z $SED ]] && type -p gsed >/dev/null 2>&1; then
    SED=gsed
fi
: ${SED=sed}

if [[ -z $FIND ]] && type -p gfind >/dev/null 2>&1; then
    FIND=gfind
fi
: ${FIND=find}

for tool in "$GREP" "$SED" "$FIND"; do
    if ! $tool --version 2>&1 | head -n1 | grep -q GNU; then
        err 'ERROR: GNU version of %s required' "$tool"
    fi
done

while [[ $# -gt 0 ]]; do
    if ((saw_dd)); then
        args+=("$1")
    elif [[ $1 == '--' ]]; then
        saw_dd=1
    elif [[ $1 == '--binaries' ]]; then
        want_binaries=1
    elif [[ $1 == '--vcs' ]]; then
        want_vcs=1
    elif [[ $1 == '--autoconf' ]]; then
        want_autoconf=1
    elif [[ $1 == '--ugly' ]]; then
        want_ugly=1
    elif [[ $1 == '--changelogs' ]]; then
        want_changelogs=1
    elif [[ $1 == '--build-files' ]]; then
        want_build_files=1
    elif [[ $1 == '--backups' ]]; then
        want_backups=1
    elif [[ $1 == '--re' ]]; then
        shift
        if [[ $# -eq 0 ]]; then
            err '--re requires an argument'
        fi
        have_re=1
        re=$1
    elif [[ $1 == '--re='* ]]; then
        have_re=1
        re=${1:6}
    elif [[ $1 == '--grep-option' ]]; then
        shift
        if [[ $# -eq 0 ]]; then
            err '--grep-option requires an argument'
        fi
        grep_opts+=("$1")
    elif [[ $1 == '--grep-option='* ]]; then
        grep_opts+=("${1:14}")
    elif [[ $1 == '--find-option' ]]; then
        shift
        if [[ $# -eq 0 ]]; then
            err '--find-option requires an argument'
        fi
        find_opts+=("$1")
    elif [[ $1 == '--find-option='* ]]; then
        find_opts+=("${1:14}")
    elif [[ $1 == '--parallel-option' ]]; then
        shift
        if [[ $# -eq 0 ]]; then
            err '--parallel-option requires an argument'
        fi
        parallel_opts+=("$1")
    elif [[ $1 == '--parallel-option='* ]]; then
        parallel_opts+=("${1:18}")
    elif [[ $1 == '-p' || $1 == '--pager' ]]; then
        want_pager=1
    elif [[ $1 == '--I='* ]]; then
        grep_opts+=("--include=${1:4}")
    elif [[ $1 == '--help' ]]; then
        cat <<EOF
$prgname [OPTIONS] PATTERN [DIR1] [DIR2...]
$prgname [OPTIONS] [DIR1] [DIR2...] --re PATTERN [DIR3...]

  Convenient wrapper for grep-like tools.

  --binaries

    Search for matches in binary files.

  --vcs

    Search for matches inside VCS metadata directories.

  --autoconf

    Search for matches inside autoconf-generated files.

  --ugly

    Use bare grep output without line numbers or color.

  --changelogs

    Include changelog files.

  --build-files

    Include miscellaneous internal build files.

  --backups

    Include files that look like backup files.

  --re PATTERN
  --re=PATTERN

    Search for this pattern.  This option is useful when
    it is inconvenient to list the pattern before the
    directories to search.

  --grep-option OPTION
  --grep-option=OPTION

    Supply OPTION directly to grep.  Note that options
    beginning with \`-' and not described here are automatically
    given to grep.

  --find-option OPTION
  --find-option=OPTION

    Supply OPTION directly to find.

  -p --pager

    Send output to pager, making sure to preserve color.

  --I=INC

    Convenient alias for grep --include=INC.

Help for $GREP follows

EOF
        $GREP --help
        exit 0
    elif [[ $1 = -* ]]; then
        if [[ $1 = -[^-]*h* ]]; then
            filenames_and_line_numbers=0
        fi
        grep_opts+=("$1")
    else
        args+=("$1")
    fi
    shift
done

if ((!have_re)); then
    if [[ ${#args[@]} -eq 0 ]]; then
        err 'no pattern supplied'
    fi
    re=${args[0]}
    args=("${args[@]:1}")
fi

if ((!want_ugly)); then
    if ((filenames_and_line_numbers)); then
        grep_opts+=(--with-filename --line-number)
    fi

    # Because parallel connects grep to a pipe, grep doesn't think
    # it's talking to a terminal that can display color.  Correct this
    # misconception and force-enable color if we're talking to a tty
    # or if we're going to be sending output to a pager we know will
    # support color.
    if [[ -t 1 ]] || ((want_pager)); then
        grep_opts+=(--color=always)
    fi
fi

if ((!want_changelogs)); then
    find_opts+=(-not -name 'ChangeLog'
                -not -name 'ChangeLog[-.]*')
fi

if ((!want_build_files)); then
    # The Linux kernel build system generates these
    find_opts+=(-not -name '.*.o.cmd'
                -not -name '*.o.d'
                -not -name '.tmp_System.map')
    # Buck
    find_opts+=(-not -path '*/buck-out/*')
    find_opts+=(-not -path '*/buck-cache/*')
fi

if ((!want_backups)); then
    find_opts+=(-not -name '*.*~*')
fi

if ((!want_binaries)); then
    find_opts+=(-not -name '*.o'
                -not -name '*.a'
                -not -name '*.so.*'
                -not -name '*.so')
    grep_opts+=(-I)
fi

if ((!want_vcs)); then
    find_opts+=(-not -path '*/.svn/*')
    find_opts+=(-not -path '*/.git/*')
    find_opts+=(-not -path '*/.pc/*')
    find_opts+=(-not -path '*/.bzr/*')
    find_opts+=(-not -path '*/.hg/*')
    find_opts+=(-not -path '*/RCS/*')
    find_opts+=(-not -path '*/*.xcodeproj/*')
fi

if((!want_autoconf)); then
    find_opts+=(-not -path '*/.deps/*')
    find_opts+=(-not -path '*/autom4te.cache/*')
    find_opts+=(-not -path '*.dep*')
    find_opts+=(-not -name 'configure')
    find_opts+=(-not -name 'config.log')
    find_opts+=(-not -name 'config.status')
    find_opts+=(-not -name 'libtool')
fi

if [[ ${#args[@]} -eq 0 ]]; then
    args+=(.)
fi

run_grep_script=
found_sentinel=

cleanup() {
    if [[ -f "$run_grep_script" ]]; then
        /bin/rm -f "$run_grep_script"
    fi
    if [[ -f "$found_sentinel" ]]; then
        /bin/rm -f "$found_sentinel"
    fi
}
trap cleanup EXIT SIGINT SIGTERM

# Create a sentinel file to record whether we found any
# matches. The file starts off empty: in the grep-running script, we
# examine grep's exit status, and if grep found at least one match, we
# put a byte in the sentinel file. After we've run all our greps, we
# just test the sentinel file to determine whether we found any
# matches overall.
found_sentinel=$(mktemp -t ppgrep-run-found-XXXXXX)

# Before we run find and grep in anger, run grep manually against
# /dev/null so that we can catch any usage errors. This way, we print
# one error message, not one for each grep parallel spawns.
set +e
( exec -a "$prgname" $GREP "${grep_opts[@]}" -- "$re" /dev/null >/dev/null )
rs=$?
set -e
if ((rs >= 2)); then
    exit $rs
fi

# Create a temporary script that execs grep for us so that we don't
# have to list grep command line options on parallel's command
# line. This way, we avoid issues with grep arguments containing
# parallel placeholders.
run_grep_script=$(mktemp -t ppgrep-run-XXXXXX)
{
    printf '( exec -a %q %s' "$prgname" "$GREP"
    for grep_arg in "${grep_opts[@]}"; do
        printf ' %q' "$grep_arg"
    done
    printf ' -- %q "$@")\n' "$re"
    # Grep exits with status 1 if it completed successfully, but
    # didn't find anything.  In this case, we want to return zero so
    # that parallel doesn't think we actually failed.
    printf 'es=$?\n'
    printf 'if [[ $es -eq 0 ]]; then echo 1 > %q && exit 0; fi\n' \
           "$found_sentinel"
    printf 'if [[ $es -eq 1 ]]; then exit 0; fi\n'
    printf 'exit $es\n'
} > "$run_grep_script"

filter_find_stderr() {
    local line
    while read -r line; do
        if [[ $line = *': Too many levels of symbolic links' ]]; then
            continue
        fi
        if [[ $line = *': Permission denied' ]]; then
            continue
        fi
        printf >&2 '%s\n' "$line"
    done
}

# Actually perform the search
enumerate_files() {
    local stage_exit=0
    local dir

    for dir in "${args[@]}"; do
        if [[ dir = -* ]]; then
            dir=./$dir
        fi

        if ! exec -a "$prgname" $FIND -L "$dir" -type f "${find_opts[@]}" -print0 \
             2> >(filter_find_stderr) \
           | $SED -z 's,^\./,,';
        then
            stage_exit=2
        fi
    done
    return $stage_exit
}

: ${PARALLEL=parallel}
parallel_executable=$(type -p "$PARALLEL" || true)
if [[ -z $parallel_executable ]]; then
    err "parallel program [called '%s'] not found" "$PARALLEL"
fi

dotdir=$HOME/.ppgrep
if ! [[ -d $dotdir ]]; then
    mkdir -p "$dotdir"
fi
cache_file=$dotdir/cache

cached_parallel_executable=
cached_parallel_version=
source "$cache_file" 2>/dev/null || true
if { [[ $cached_parallel_executable != "$parallel_executable" ]] \
         || [[ $parallel_executable -nt $cache_file ]]; };
then
    cached_parallel_executable=$parallel_executable
    cached_parallel_version=$($PARALLEL --version 2>&1 | head -n1)
    if ! [[ $cached_parallel_version == "GNU parallel "* ]]; then
        err "No GNU parallel found [%s]" "$parallel_version"
    fi
    printf 'cached_parallel_executable=%q\ncached_parallel_version=%q\n' \
           "$parallel_executable" "$cached_parallel_version" > "$cache_file"
fi

if ! [[ $cached_parallel_version == "GNU parallel 2013"* ]]; then
    parallel_opts=(--no-notice "${parallel_opts[@]}")
fi

parallel_opts=(-0 -k -n $max_args_per_grep -m "${parallel_opts[@]}")

set +e
if ((want_pager)); then
    enumerate_files \
        | "$parallel_executable" "${parallel_opts[@]}" $BASH "$run_grep_script" \
        | ${PAGER-less} -R
else
    enumerate_files \
        | "$parallel_executable" "${parallel_opts[@]}" $BASH "$run_grep_script"
fi
mcret=$?
set -e

if ((mcret==0)); then
    if ! [[ -s "$found_sentinel" ]]; then
        exit 1 # Successfully found nothing
    fi
    exit 0
else
    exit 2
fi
